---
ports_to_open:
  - 22 # ssh port, should stay open 
  - 80 # web server port
index_name_to_copy: index.html.j2
index_path_to_paste: /var/www/html/
index_name_to_paste: index.html

ubuntu_vms:
  packages:
    - name: nginx
      version: 1.18.0-6ubuntu14.6
fedora_vms:
  packages:
    - name: httpd
      version: 2.4.57