---
- name: Install the nginx web server for ubuntu_vms
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Install the httpd web server for fedora_vms
  import_tasks: fedora.yml
  when: ansible_facts['distribution']|lower == 'fedora'